### ISSUE TITLE
Using magic provider or signer with standard Nethereum interface

### ISSUE THREAD

**Issue by adam-maj** [magiclabs/magic-unity#3]
I've tried using this package in my Unity project - have just used the `Login` and `Logout` functions in the prefab for now, and works like a charm. I'm using the Nethereum package already externally, so I don't want to use the wrapped interfaces in this package that are shown in the README, but instead want to just create a new `Account` and `Web3` instance with Nethereum, but I want to use the connected signer from this magic.link connection.

ie. I want a setup similar to the following

```csharp
// I need some way to create a Nethereum.Web3.Accounts.Account instance with the magic private key (this isn't the right syntax)
var account = new Account(magic);
// Then I can use it to create my own Nethereum.Web3.Web3 instance and use it like usual
var provider = new Web3(account, rpcUrl);
```

Is there any way to extract the signer/use this type of setup. I've tried looking through the package but haven't found anything obvious so far (was looking for a place where the Nethereum Web3 or Account interface is stored/wrapped internally but couldn't find one)

Looking forward to implementing this flow! @Ethella

**Comment by Ethella** [comment]
@adam-maj Hey Adam, thank you for the feedback. 

First of all, Magic is a non-custodial key management system where the private key is not visible or can be fetched from us. In such a case, the signing process will not be done locally in your Unity project, but remotely in a third-party context (our auth relayer). As a consequence, the libraries that depend on private keys will not be feasible in our use case.

Secondly, 
The reason why we didn't include a `web3()` flow is because Nethereum has not included `Nethereum.Web` in their Unity releases. And we didn't successfully make a workaround to it.

Here are the released files, https://github.com/Nethereum/Nethereum/releases/tag/4.6.1

However, it seems like you've successfully installed the `Nethereum.Web3` package in your Unity project and make it run. Could you share with us your installation steps and DLLs being used in your project? I'll see if it's possible to make a workaround with `Nethereum.Web3`

**Comment by adam-maj** [comment]
@Ethella Thanks for the response - right forgot about the custodial aspect, so assume I need an API that will send the correct transaction payloads in authenticated requests to magic endpoints, which I'm guessing is what the API in the README does.

However, the Nethereum transaction API from `Account` or `Web3` should just expose a simple provider interface that involves signing messages, etc. that can be used to send signed transactions/use the same API as standard Nethereum interface - this would allow a magic provider to be interchangeable in codebases with other providers like WalletConnect, MetaMask, etc. that handle private keys in different ways.

This exists in TypeScript for example, where there is a `MagicProvider`/`MagicConnector` (not sure if its built by magic or not) that let's you use the magic API with standard `ethers.js`/`web3.js` functionality even though under the hood its not signing messages with private keys directly but instead making API requests - does such a thing exist for C# as well with a compatible Nethereum interface/is there a way I could help to add this functionality in.

As far as my setup, I have a separate dotnet package where I have `Nethereum.Web3` as a dependency (installs the DLLs into the package), and when I build my own package, the DLL works out of the box in Unity (and the Nethereum.Web3 functionality is working) - it just took some fiddling with the configuration file for my package build.

In my package, I want to support multiple different connectors (via Nethereum.Web3) which is why I want to make sure that I have a compatible interface.

Thanks for the help

**Comment by adam-maj** [comment]
@Ethella Just wanted to follow up on this one :)

**Comment by Ethella** [comment]
We are on a national holiday. But you can still try to pull the latest main, as I have included Nethereum.web3 in the dependency

**Comment by adam-maj** [comment]
Thanks a lot, enjoy the holidays! Will circle back on this during the week, will be playing around with it for now

**Comment by Ethella** [comment]
@adam-maj Just took a quick look. I think you may pull the latest `main` and call `web3` now
```c#
            var web3 = new Web3(Magic.Instance.Provider);
            var accounts = await web3.Eth.Accounts.SendRequestAsync();
            print($"MagicUnity {accounts[0]}");
```
